name: Go
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Go 1.12"
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.4
      - name: "Check out code into the Go module directory"
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/cloudflare/cfssl
      # - env:
      #     GOPATH: /home/runner/work/cloudflare/go
      #   name: Test
      #   run: ./test.sh
      - env:
          GOPATH: /home/runner/work/cloudflare/go
        name: Build
        run: make
